[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
markers = [
    "sub_dir: Creates custom subdirectory for simulating the file system for tests",
]
